### ISSUE TITLE
wallapatta npm command fails because of incorrect jsdom version

### ISSUE THREAD

**Issue by chethiya** [vpj/wallapatta#12]
I get following error:

```
coffee -c -o templates templates/*.coffee
wallapatta --blog blog.yaml --output ../blog --static
(node:65922) [DEP0016] DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
/Users/chethiya/tools/nodejs/lib/node_modules/wallapatta/file.js:13
      return jsdom.env('<div id="main"></div><div id="sidebar"></div>', function(err, window) {
                   ^

TypeError: jsdom.env is not a function
    at render (/Users/chethiya/tools/nodejs/lib/node_modules/wallapatta/file.js:13:20)
    at Object.exports.blog (/Users/chethiya/tools/nodejs/lib/node_modules/wallapatta/wallapatta.js:162:9)
    at Timeout.handle [as _onTimeout] (/Users/chethiya/tools/nodejs/lib/node_modules/wallapatta/cli.js:22:25)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

make: *** [all] Error 1
```

Looks like setting jsdom version to 9.12.0 solves this problem.

**Comment by vpj** [comment]
Can you create a pull request?
